### ISSUE TITLE
cannot use null in socket_select()

### ISSUE THREAD

**Issue by waitman** [orangeable/php-websocket#2]
per doc: 

> "Due a limitation in the current Zend Engine it is not possible to pass a constant modifier like null directly as a parameter to a function which expects this parameter to be passed by reference. Instead use a temporary variable or an expression with the leftmost member being a temporary variable"

`socket_select($changed, NULL, NULL, 0, 10);`

needs to be something like

`socket_select($changed, $w, $e, 0, 10);`

**Comment by orangeable** [comment]
A solution has been added and pushed. Thanks!
