### ISSUE TITLE
allow specification of TLS certs

### ISSUE THREAD

**Issue by JustinWebDev** [orangeable/php-websocket#3]
I don't know if this is possible with socket_create() (it is with stream_context_create()).  If a developer doesn't have the ability to modify the webserver configuration to specify the TLS cert files (as you show [here](https://orangeable.com/server/secure-websocket)), then there is no way for the websocket server to know about the certs, as far as I can determine, and so the socket does not correctly connect with the client.

**Comment by orangeable** [comment]
Administrative access with a Ubuntu and Apache setup are what these examples follow. You can find more information on the prerequisites in the article: https://orangeable.com/javascript/chat#prerequisites
